# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
- job: BuildAndRunNodeAutomation
  displayName: "Build and Run Node.js API Automation"
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: octane-start-task@2
    inputs:
      OctaneServiceConnection: 'SitaValueEdgeTrial'
      WorkspaceList: '1002'
      CreatePipelineCheckbox: true
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      echo Installing dependencies...
      npm install
    displayName: 'npm install'

# Step to create the .env file with pipeline parameters
  - script: |
      echo Creating .env file with parameters...
      echo SONAR_PROJECT_KEY=$(SONAR_PROJECT_KEY) >> .env
      echo VALUEEDGE_MANUAL_ACTION_ID=$(VALUEEDGE_MANUAL_ACTION_ID) >> .env
      echo VALUEEDGE_QUALITY_GATE_ID=$(VALUEEDGE_QUALITY_GATE_ID) >> .env
      echo VALUEEDGE_RELEASE_PROCESS_ID=$(VALUEEDGE_RELEASE_PROCESS_ID) >> .env
    displayName: 'Generate .env file from parameters'

  - script: |
      echo Running Node.js application...
      node index.mjs
    displayName: 'Run Node.js Application'

  - task: octane-end-task@2
    inputs:
      OctaneServiceConnection: 'SitaValueEdgeTrial'
      WorkspaceList: '1002'